server:
  port: 8003
eureka:
  instance:
    hostname: eureka-service3
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@eureka-service1:8001/eureka/,http://admin:admin@eureka-service2:8002/eureka/
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin




